x, y, z = 8, 4, 2 # the values of x, y, and z can be written in one line.
print(x, y, z)
print(x)
print(y)
print(z)
print(x/y)
print(x/z)
print(y/z)
print(x+y+z)
print(x*y*z)
print(x-y-z)
print(x/y/z)
print(x//y//z)
print(x%y%z)